import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import mongoose from "mongoose";
import Product from "@/models/Product"
import Topproduct from '@/models/Topproduct';
import { useRouter } from 'next/router';
import { useRef } from 'react';

// const inter = Inter({ subsets: ['latin'] })

function Home({ addToCart, topproducts }) {

  const router = useRouter()
  // const downButton = useRef(0)
  const weightsList = useRef(null)

  // weight list down function 
  const weightListDown = async (e) => {

    if (e.target.nextElementSibling.style.visibility == "hidden") {
      e.target.nextElementSibling.style.visibility = "visible";
    }
    else {
      e.target.nextElementSibling.style.visibility = "hidden";
    }
  }


  // const productPage = (itemSlug)=>{

  //   router.push(`product/${itemSlug}`)
  // }

  return (
    <>
      <Head>
        <title>BPS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* Upper ad section */}
      <section className={styles.firstintro}>
        <div className={styles.heading}>
          <h3>Welcome to our online store</h3>
          <h1>Baba Provision Store</h1>
          <p>For Genuine Products</p>
        </div>
      </section>

      {/* feature section */}
      <section id={styles.feature}>
        <div className={styles.insidefeature}>
          <div className={`${styles.feature} ${styles.feat1}`}>
            <Image src="/pic1.png"
              alt="Feature img" width={50} height={50} />

            <div id={styles.freeDel}>
              <p id={styles.free1}>Free</p>
              <p id={styles.free2}>Delivery</p>
            </div>
          </div>

          <div className={`${styles.feature} ${styles.feat2}`}>
            <Image src="/pic2.png" alt="Feature img" width={50} height={50} />

            <div id={styles.Quality}><p id={styles.quality1}> Quality</p>
              <p id={styles.quality2}>You can trust</p>
            </div>
          </div>

          <div className={`${styles.feature} ${styles.feat3}`}>
            <Image src="/pic3.png" alt="Feature img" width={50} height={50} />

            <div id={styles.FastDel}><p id={styles.FD1}>Fastest</p>
              <p id={styles.FD2}>Delivery</p>
            </div>
          </div>

          <div className={`${styles.feature} ${styles.feat4}`}>
            <Image src="/pic4.png" alt="Feature img" width={50} height={50} />
            <div id={styles.SecurePay}><p id={styles.SP1}>Secure</p>
              <p id={styles.SP2}>Payment</p>
            </div>
          </div>

          <div className={`${styles.feature} ${styles.feat5}`}>
            <Image src="/pic5.png" alt="Feature img" width={50} height={50} />

            <div id={styles.COD}><p id={styles.COD1}>Cash On</p>
              <p id={styles.COD2}>Delivery</p>
            </div>
          </div>
        </div>
      </section>


      {/* advertisement (section) */}
      <section id={styles.adSection}>

      </section>


      {/* best product display (section) */}
      <section className={styles.topProduct}>
        <div className={styles.topContent}>
          <div className={styles.topDetail}>
            <div className={styles.topHeading}><h3>Top Products</h3></div>
          </div>

          <div className={styles.topProductCards}>
            {/* product card */}
            {topproducts.map((item) => {
              return <div key={item._id} className={styles.topCard}>
                <div className={styles.topCardImg}><img src={item.img} height={150} width={150} alt='' /></div>

                <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

                <Link href={`/Product/${item.slug}`}><div className={styles.topProductDetail1}>
                  <div className={styles.topName}>{item.title}</div>
                  {!item.size2 && <div className={styles.topWeight}>{item.size}</div>}
                  {/* for multiple size  */}
                  {item.size2 && <>
                    <div onClick={weightListDown} className={styles.topWeightMultiple}>{item.size} <Image src={'/downwards-key.png'} className={styles.weightDownkey} width={12} height={12} alt='' />
                    </div>

                    <div ref={weightsList} className={styles.weightList}>
                      <ul>
                        <li>{item.size}1</li>
                        <li>{item.size}2</li>
                        <li>{item.size}3</li>
                      </ul>
                    </div>
                  </>}
                </div></Link>
                <div className={styles.topProductDetail2}>
                  <div className={styles.topPrice}><span>₹</span>{item.price}</div>
                  <div className={styles.topAdd}><button onClick={(e) => {
                    e.preventDefault()
                    addToCart(item.id, 1, item.title, item.price, item.size, item.img)
                  }}>ADD</button>
                  </div>
                </div>
              </div>
            })}
          </div>
        </div>
      </section>


      {/* spices section */}
      <section id={styles.spicesSection}>
        <p className={styles.spicesTagline}>Cook your food with best <span className={styles.tagSpan}>Spices</span></p>
        <button className={styles.btn1}>Buy Now</button>
      </section>


      {/* shop - category  section*/}
      <section className={styles.catProduct}>
        <div className={styles.catContent}>

          <div className={styles.catDetail}>
            <div className={styles.catHeading}><h3>Shop by Categories</h3></div>
          </div>
          
          {/* container  */}
          <div className={styles.catCardContainer}>
            {/* 1 */}
            <Link href={`/catProducts/biscuits-and-snacks`}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Biscuits & Snacks</div>
            </div></Link>
            {/* 2 */}
            <Link href={`/catProducts/dryfruits`}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/dryfruits.jpg'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Dryfruits</div>
            </div></Link>
            {/* 3 */}
            <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Tea & Coffee</div>
            </div></Link>
            {/* 4 */}
            <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Dal & Rice</div>
            </div></Link>
            {/* 5 */}
            <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Masala</div>
            </div></Link>
            {/* 6 */}
            <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Atta</div>
            </div></Link>
            {/* 7 */}
             <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Oil & Ghee</div>
            </div>
            {/* 8 */}</Link>
             <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Salt & Sugar</div>
            </div>
            {/* 9 */}</Link>
             <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Personal & Baby care</div>
            </div></Link>
            {/* 10 */}
             <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Cleaning & Household</div>
            </div></Link>
            {/* 11 */}
             <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Pooja-path</div>
            </div></Link>
            {/* 12 */}
             <Link href={''}><div className={styles.catCard}>
              <div className={styles.catImg}><Image src={'/chips.jfif'} width={100} height={140} alt='' /></div>
              <div className={styles.catName}>Salt & Sugar</div>
            </div></Link>
          </div>
        </div>
      </section >


      {/* oil section */}
      <section id={styles.oilsSection}>
        <p className={styles.oilsTagline}>Cook your food with best <span className={styles.tagSpan}>Oils</span></p>
        <button className={styles.btn2} >Buy Now</button>
      </section>



      {/* grocery-section */}
      <section className={styles.groceryProduct}>
        <div className={styles.topContent}>
          <div className={styles.groceryTopDetail}>
            <div className={styles.groceryTopHeading}><h3>Grocery & Staples</h3></div>
            <div className={styles.groceryTopLink}><Link href={''}>See All</Link></div>
          </div>

          {/* product card */}
          <div className={styles.topProductCards}>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
          </div>
        </div>
      </section >


      {/* personal care   (section) */}
      <section className={styles.perCareProduct}>
        <div className={styles.topContent}>
          <div className={styles.pcTopDetail}>
            <div className={styles.pcTopHeading}><h3>Personal Care</h3></div>
            <div className={styles.pcTopLink}><Link href={''}>See All</Link></div>
          </div>

          {/* product card */}
          <div className={styles.topProductCards}>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
          </div>
        </div>
      </section>


      {/* Buiscuit & baker  (section) */}
      <section className={styles.bakersSection}>
        <p className={styles.bakersTagline}>Improve your mood with best <span className={styles.bakerstagSpan}>Biscuits</span></p>
        <Link href={'/products'}><button className={styles.btn3}>Buy Now</button></Link>
      </section>


      {/* home cleaning *****(section) */}
      <section className={styles.cleaningProduct}>
        <div className={styles.topContent}>
          <div className={styles.homeTopDetail}>
            <div className={styles.homeTopHeading}><h3>Cleaning & Household</h3></div>
            <div className={styles.homeTopLink}><Link href={''}>See All</Link></div>
          </div>

          {/* product card */}
          <div className={styles.topProductCards}>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
            <div className={styles.topCard}>
              <div className={styles.topCardImg}><Image src={'/Maggi.jpg'} height={200} width={200} alt='' /></div>

              <div className={styles.wishlist}><button><Image src={'/whiteheart.png'} height={20} width={20} alt='' /></button></div>

              <div className={styles.topProductDetail1}>
                <div className={styles.topName}>2 Minute Maggi Noodles Noodles Noodle noodle</div>
                <div className={styles.topWeight}>70 g</div>
              </div>

              <div className={styles.topProductDetail2}>
                <div className={styles.topPrice}><span>₹</span>14</div>
                <div className={styles.topAdd}><button>ADD</button></div>
              </div>
            </div>
          </div>
        </div>
      </section >
    </>
  )

}




export async function getServerSideProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONG0_URI)
  }

  let topproducts = await Product.find({ topCategory: "yes" })
  return {
    props: { topproducts: JSON.parse(JSON.stringify(topproducts)) }
  }
}

export default Home




